version: '3.7'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    container_name: api-medic
    build:
      context: .
    image: medical-api
    depends_on:
      - db
    ports:
      - 4000:4000
    environment:
      NODE_ENV: prd
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local