version: '3.7'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  # api:
  #   container_name: api-medic
  #   build:
  #     context: ./
  #     target: production
  #   image: api-medic
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   environment:
  #     NODE_ENV: production
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: postgres
  #   links:
  #     - db
  #   volumes:
  #     - './:/src'
volumes:
  db:
    driver: local